name:                dominion-api
version:             0.1.0.0
github:              "https://github.com/robinzigmond/dominion-api"
license:             BSD3
author:              "Robin Zigmond"
maintainer:          "Robin Zigmond"
copyright:           "Robin Zigmond"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/robinzigmond/dominion-api/blob/master/README.md>

dependencies:
- base >= 4.7 && < 5
- transformers
- text
- aeson
- wai
- warp
- servant-server
- persistent
- persistent-postgresql
- persistent-template
- monad-logger
- resourcet
- unordered-containers
- http-api-data
- casing
- bytestring
- esqueleto
- servant-docs
- http-types
- cmark
- http-media
- lens
- base-compat
- string-conversions
- containers
- mtl
- wai-logger

library:
  source-dirs: src

executables:
  dominion-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dominion-api

tests:
  dominion-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dominion-api
    - hspec
    - servant-client
    - http-client
    - servant-quickcheck
    - hspec-wai
